import { Link } from 'react-router-dom';
import SectionHeading from '../components/SectionHeading';
import ProjectCard from '../components/ProjectCard';
import Icon from '../components/Icons';
import { projects, skills } from '../data/siteData';

export default function Home() { return <>
  <section className="hero container"><div className="hero-copy"><div className="availability"><span className="pulse-dot"/> Available for select projects</div><h1>Turning ideas into<br/><span className="gradient-text">digital experiences.</span></h1><p className="hero-description">I'm Clemson, a developer and creative thinker who builds clean, useful and engaging digital products for people and businesses.</p><div className="hero-actions"><Link to="/projects" className="button button-primary">Explore my work <Icon name="arrow"/></Link><Link to="/contact" className="button button-ghost">Get in touch <Icon name="external"/></Link></div><div className="hero-meta"><span><Icon name="pin"/> Based in Ghana</span><span className="meta-divider"/><span>Developer · Creative</span></div></div><div className="hero-art"><div className="art-glow"/><div className="art-grid"/><div className="art-card art-card-back"><span className="code-label">CREATIVE / 01</span><div className="code-lines"><i/><i/><i/><i/><i/></div></div><div className="art-card art-card-front"><div className="art-card-head"><span>BUILDING THE WEB</span><span className="live-indicator"/></div><div className="orbital"><div className="orbital-ring ring-one"/><div className="orbital-ring ring-two"/><div className="orbital-core">cj<span>.</span></div><i className="orbit-dot dot-one"/><i className="orbit-dot dot-two"/><i className="orbit-dot dot-three"/></div><div className="art-card-foot"><span>DESIGN</span><span>DEVELOP</span><span>CREATE</span></div></div><div className="floating-chip chip-one"><Icon name="code"/> Clean code</div><div className="floating-chip chip-two"><Icon name="palette"/> Good design</div><span className="art-cross cross-one">+</span><span className="art-cross cross-two">+</span></div><div className="hero-scroll"><span/> SCROLL TO EXPLORE</div></section>
  <section className="trust-strip"><div className="container trust-inner"><span>CURIOUS BY NATURE</span><span className="trust-line"/><span>CREATIVE BY DESIGN</span><span className="trust-line"/><span>BUILT WITH PURPOSE</span></div></section>
  <section className="section container intro-section"><div className="intro-label"><span className="eyebrow"><i/> A LITTLE ABOUT ME</span><span className="intro-index">01 — 04</span></div><div className="intro-content"><h2>I enjoy solving problems with <span className="muted-text">technology, creativity and a healthy obsession with the details.</span></h2><Link to="/about" className="text-link">More about me <Icon name="arrow"/></Link></div></section>
  <section className="section container"><SectionHeading eyebrow="SELECTED WORK" title="A few things I've built." text="A selection of projects where ideas meet thoughtful execution."/><div className="project-grid">{projects.slice(0,3).map(project => <ProjectCard key={project.number} project={project}/>)}</div><div className="center-action"><Link to="/projects" className="button button-ghost">View all projects <Icon name="arrow"/></Link></div></section>
  <section className="section skills-section"><div className="container skills-layout"><div><SectionHeading eyebrow="MY TOOLKIT" title="The tools behind the work." text="A growing set of skills and technologies I use to bring ideas to life."/><Link to="/about" className="text-link">Explore my skills <Icon name="arrow"/></Link></div><div className="skill-cloud">{skills.map((skill,i)=><span className="skill-pill" key={skill}><b>0{i+1}</b>{skill}</span>)}</div></div></section>
  <section className="section container home-cta"><div className="cta-orb"/><span className="eyebrow"><i/> HAVE SOMETHING IN MIND?</span><h2>Let's build something<br/><span className="gradient-text">worth remembering.</span></h2><Link to="/contact" className="button button-primary">Start a conversation <Icon name="arrow"/></Link></section>
</>; }
