import { Link } from 'react-router-dom';
import SectionHeading from '../components/SectionHeading';
import Icon from '../components/Icons';
const services = [
 {n:'01',icon:'code',title:'Web Development',text:'Responsive, fast and accessible websites built around your goals and the people using them.',items:['Business & portfolio websites','React front-end development','Landing pages & web interfaces']},
 {n:'02',icon:'palette',title:'UI & Digital Design',text:'Clean and considered interfaces that make products easier to understand and more enjoyable to use.',items:['Website and app interface design','Wireframes & visual direction','Design systems and components']},
 {n:'03',icon:'mobile',title:'Application Development',text:'Practical application experiences that help turn everyday processes into smoother digital workflows.',items:['Application interface development','Dashboard experiences','API and Firebase integration']}
];
export default function Services() { return <main className="page container"><div className="page-intro"><span className="eyebrow"><i/> WHAT I CAN DO</span><h1>Good ideas deserve<br/><span className="gradient-text">great execution.</span></h1><p>From the first sketch to the final interaction, I help shape digital experiences with purpose.</p></div><section className="section services-section"><SectionHeading eyebrow="SERVICES" title="Ways we can work together." text="A thoughtful approach, tailored to what your project actually needs."/><div className="service-list">{services.map(s=><article className="service-item" key={s.n}><div className="service-number">/{s.n}</div><div className="service-icon"><Icon name={s.icon}/></div><div className="service-main"><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(item=><li key={item}><Icon name="check"/>{item}</li>)}</ul></div><span className="service-arrow"><Icon name="arrow"/></span></article>)}</div></section><section className="home-cta service-cta"><span className="eyebrow"><i/> HAVE A PROJECT?</span><h2>Let's figure out<br/><span className="gradient-text">what's possible.</span></h2><Link to="/contact" className="button button-primary">Tell me about it <Icon name="arrow"/></Link></section></main>; }
